### ISSUE TITLE
possible to enable `gimap` to get access to gmail specific search terms 

### ISSUE THREAD

**Issue by maxandersen** [oblac/jodd-mail#1]
## Current behavior

at the moment seems just plain imap is supported; would be interesting to access `gimap` protocol https://javaee.github.io/javamail/docs/api/com/sun/mail/gimap/package-summary.html

## Expected behavior

have way to enable `gimap` protocol to allow use of gmail search specific terms

**Comment by Daniellainand** [comment]
`
public static void sendEmail(String to, String subject, String body) {
        try {
            Email email = Email.create()
                    .from("noreply@example.com")
                    .to(to)
                    .subject(subject)
                    .textMessage(body)
                    .htmlMessage("<b>HTML</b> message...")
                    .priority(PRIORITY_HIGHEST);

            SmtpServer smtpServer = MailServer.create()
                    .ssl(false)
                    .host("mail.example.eu")
                    .port(587)
                    .auth("noreply@example.com", "examplepassword")
                    .buildSmtpMailServer();

            SendMailSession session = smtpServer.createSession();
            session.open();
            session.sendMail(email);
            session.close();

            System.out.println("E-Mail erfolgreich versendet an: " + to);
        } catch (Exception e) {
            e.printStackTrace();
            System.err.println("Fehler beim Senden der E-Mail: " + e.getMessage());
        }
    }`


Error code: 
`
jodd.mail.MailException: Open session error; <--- javax.net.ssl.SSLException: Unsupported or unrecognized SSL message
	at jodd.mail@7.0.0/jodd.mail.MailSession.open(MailSession.java:87)
	at jodd.mail@7.0.0/jodd.mail.SendMailSession.open(SendMailSession.java:51)
	at de.abc13/de.abc13.utils.mail.SendLoginDaten.sendEmail(SendLoginDaten.java:30)
	at de.abc13/de.abc13.mitarbeiter.MitarbeiterHinzufügen.lambda$mitarbeiterhinzufügenbtn$0(MitarbeiterHinzufügen.java:79)
	at de.abc13/de.abc13.database.CallbackTask.run(CallbackTask.java:15)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:839)
Caused by: jakarta.mail.MessagingException: Could not connect to SMTP host: mail.kitffa.eu, port: 587;
  nested exception is:
	javax.net.ssl.SSLException: Unsupported or unrecognized SSL message
	at org.eclipse.angus.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:2245)
	at org.eclipse.angus.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:729)
	at jakarta.mail.Service.connect(Service.java:367)
	at jakarta.mail.Service.connect(Service.java:225)
	at jakarta.mail.Service.connect(Service.java:174)
	at jodd.mail@7.0.0/jodd.mail.MailSession.open(MailSession.java:85)
	... 7 more
Caused by: javax.net.ssl.SSLException: Unsupported or unrecognized SSL message
	at java.base/sun.security.ssl.SSLSocketInputRecord.handleUnknownRecord(SSLSocketInputRecord.java:457)
	at java.base/sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:175)
	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:111)
	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1507)
	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1417)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:456)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:427)
	at org.eclipse.angus.mail.util.SocketFetcher.configureSSLSocket(SocketFetcher.java:628)
	at org.eclipse.angus.mail.util.SocketFetcher.createSocket(SocketFetcher.java:401)
	at org.eclipse.angus.mail.util.SocketFetcher.getSocket(SocketFetcher.java:214)
	at org.eclipse.angus.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:2193)
	... 12 more
---[cause]------------------------------------------------------------------------
javax.net.ssl.SSLException: Unsupported or unrecognized SSL message
	at java.base/sun.security.ssl.SSLSocketInputRecord.handleUnknownRecord(SSLSocketInputRecord.java:457)
	at java.base/sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:175)
	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:111)
	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1507)
	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1417)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:456)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:427)
	at org.eclipse.angus.mail.util.SocketFetcher.configureSSLSocket(SocketFetcher.java:628)
	at org.eclipse.angus.mail.util.SocketFetcher.createSocket(SocketFetcher.java:401)
	at org.eclipse.angus.mail.util.SocketFetcher.getSocket(SocketFetcher.java:214)
	at org.eclipse.angus.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:2193)
	at org.eclipse.angus.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:729)
	at jakarta.mail.Service.connect(Service.java:367)
	at jakarta.mail.Service.connect(Service.java:225)
	at jakarta.mail.Service.connect(Service.java:174)
	at jodd.mail@7.0.0/jodd.mail.MailSession.open(MailSession.java:85)
	at jodd.mail@7.0.0/jodd.mail.SendMailSession.open(SendMailSession.java:51)
	at de.abc13/de.abc13.utils.mail.SendLoginDaten.sendEmail(SendLoginDaten.java:30)
	at de.abc13/de.abc13.mitarbeiter.MitarbeiterHinzufügen.lambda$mitarbeiterhinzufügenbtn$0(MitarbeiterHinzufügen.java:79)
	at de.abc13/de.abc13.database.CallbackTask.run(CallbackTask.java:15)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:839)
Fehler beim Senden der E-Mail: Open session error; <--- javax.net.ssl.SSLException: Unsupported or unrecognized SSL message`
